### ISSUE TITLE
replybuffer definition and idx did not match

### ISSUE THREAD

**Issue by tomaskovacik** [botletics/Arduino-AT-Command-Library#1]
hello,

thx for contribution with your lib

I have question, in your header file you define char replybuffer[255] so array for 255 chars, later in function 

bool ATcommands::sendCommand(char *command, char *reply, uint16_t timeout) {

you are indexing reply buffer with variable idx which is defined as uint16_t so up to 32k 

is it ok?

**Comment by botletics** [comment]
Sorry, I wasn't watching this repo and didn't see this until now lol. It should be OK as long as the info received doesn't go past 255 chars, but you're right, it's best to make idx uint8_t instead. I'll change it.
